spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/journaldb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    com:
#      guptem:
#        journalApp: DEBUG


